name: joyeria_app
description: "Aplicación móvil para venta de joyas con Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # Estado (Provider)
  provider: ^6.1.1

  # Utilidades
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_iconly: ^1.0.2
  google_sign_in: ^6.2.0
  google_fonts: ^6.1.0
  intl: ^0.18.1  # ✅ Aquí agregas intl

  # Carrusel
  card_swiper: ^3.0.1
  image_picker: ^1.2.0
  flutter_colorpicker: ^1.1.0
  pdf: ^3.11.0
  printing: ^5.13.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
