name: SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el código fuente
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para un análisis preciso de historial

      # 2️⃣ Instalar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"  # Cambia si usas otra versión

      # 3️⃣ Verificar versiones de Flutter y Dart
      - name: Verify Flutter and Dart
        run: |
          flutter --version
          dart --version

      # 4️⃣ Instalar dependencias
      - name: Get dependencies
        run: flutter pub get

      # 5️⃣ Ejecutar pruebas y generar reporte de cobertura
      - name: Run tests with coverage
        run: flutter test --coverage

      # 6️⃣ Ejecutar análisis de SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=docs/joyeria_christa
            -Dsonar.dart.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=lib
            -Dsonar.tests=test
            -Dsonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated_plugin_registrant.dart,**/build/**
            -Dsonar.javascript.enabled=false
            -Dsonar.typescript.enabled=false
