name: SonarCloud Analysis (Flutter)

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio completo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Configurar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Ejecutar análisis estático (lint)
      - name: Analyze code
        run: flutter analyze || true

      # 5️⃣ Ejecutar pruebas con cobertura
      - name: Run tests with coverage
        run: |
          cd docs/joyeria_christa
          flutter test --coverage || true

      # 6️⃣ Instalar Node.js (para compatibilidad)
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 7️⃣ Escanear el código en SonarCloud (solo Dart)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: "-Dsonar.nodejs.executable=node"
        with:
          projectBaseDir: docs/joyeria_christa
          args: |
            -Dsonar.projectKey=Selvin-lopez_joyeria_christa
            -Dsonar.organization=selvin-lopez
            -Dsonar.projectName="Joyeria Christa Flutter App"
            -Dsonar.language=dart
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=lib
            -Dsonar.inclusions=lib/**/*.dart
            -Dsonar.exclusions=build/**,**/*.g.dart,**/*.js,**/*.ts,**/*.jsx,**/*.tsx,**/*.yaml,**/*.json,**/*.html,**/*.css,**/generated_plugin_registrant.dart
            -Dsonar.tests=test
            -Dsonar.test.inclusions=test/**/*.dart
            -Dsonar.dart.coverage.reportPaths=coverage/lcov.info
            -Dsonar.javascript.file.suffixes=-
            -Dsonar.typescript.file.suffixes=-
            -Dsonar.javascript.enabled=false
            -Dsonar.typescript.enabled=false
            -Dsonar.cpd.exclusions=**/*.js,**/*.ts,**/*.jsx,**/*.tsx
            -Dsonar.core.codeCoveragePlugin=dart

      # 8️⃣ Validar Quality Gate (opcional)
      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: docs/joyeria_christa
          args: |
            -Dsonar.qualitygate.wait=true
