name: SonarCloud Initialization

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    name: SonarCloud Activation

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"

      - name: Get dependencies
        run: flutter pub get

      - name: Run lightweight analysis
        run: |
          echo "init" > lib/temp_sonar_init.dart
          flutter analyze || true
          echo "Minimal analysis executed."

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
