name: Análisis SonarCloud para Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Construir y analizar proyecto Flutter
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2️⃣ Configurar Flutter
      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      # 3️⃣ Configurar caché (para acelerar dependencias)
      - name: Configurar caché de paquetes
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 4️⃣ Instalar dependencias del proyecto
      - name: Instalar dependencias
        run: flutter pub get
        working-directory: docs/joyeria_christa

      # 5️⃣ Analizar código (sin detener pipeline si hay advertencias)
      - name: Analizar código
        run: |
          flutter analyze || true
        working-directory: docs/joyeria_christa

      # 6️⃣ Ejecutar pruebas con cobertura
      - name: Ejecutar pruebas con cobertura
        run: |
          flutter test --coverage || true
        working-directory: docs/joyeria_christa

      # 7️⃣ Escanear con SonarCloud
      - name: Escaneo SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: Selvin-lopez_Proyecto-QA
          SONAR_ORGANIZATION: selvin-lopez
        with:
          projectBaseDir: docs/joyeria_christa

