name: CI - Flutter + SonarCloud (estable)

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        working-directory: docs/joyeria_christa
        run: flutter pub get

      - name: Run tests with coverage
        working-directory: docs/joyeria_christa
        run: flutter test --coverage

      - name: Verify coverage file
        working-directory: docs/joyeria_christa
        run: |
          if [ ! -f coverage/lcov.info ]; then
            echo "❌ coverage/lcov.info not found"
            exit 1
          fi
          echo "✅ LCOV file found"
          head -n 5 coverage/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: docs/joyeria_christa
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
